#BSUB -J Fam-simulation-500-Miss-20
#BSUB -W 360:00
#BSUB -o /rsrch3/home/bcb/hnnguyen4/Fam-simulation-500/Miss-20/log/sim_1.out
#BSUB -e /rsrch3/home/bcb/hnnguyen4/Fam-simulation-500/Miss-20/log/sim_1.err
#BSUB -cwd /rsrch3/home/bcb/hnnguyen4/Fam-simulation-500/Miss-20
#BSUB -q vlong
#BSUB -u hnnguyen4@mdanderson.org
#BSUB -B
#BSUB -N
#BSUB -n 25
#BSUB -M 96
#BSUB -R rusage[mem=96]

module load R
Rscript sim_1.R

